### ISSUE TITLE
Add ability to treat Table as Source

### ISSUE THREAD

**Issue by nirvdrum** [mehcode/config-rs#159]
I'm looking to implement configuration for my application in a form similar to the AWS configuration file. Basically, it's an INI-style file with the notion of _profiles_ in it and each profile can set parameter values from a pool of keys. There's also a notion of _source_ profiles so you can form a linked-list of values for inheritance.

As far as I can tell, _config-rs_ doesn't support this style of configuration, favoring an approach where each "profile" would get its own configuration file. If that's a project goal, then I won't try to change it. But, looking at things, I think I can achieve what I want if I could treat a `Table` as a `Source`.

Just to make this a bit more concrete:

```yaml
profiles:
  default:
    api_key: f57ca94b6d3bdf6e8216445397bbd6e415e831d27dccaedd991d9c487aa18fa9
 
  ro-local:
    # Read-only key against localhost
    api_key: bb854ec5a5d58b4a20a48775b45f051dfcaa12a7cebfba693a24e7f1026c3341
    server_url: http://localhost:7001/graphql

  production:
    api_key: f57ca94b6d3bdf6e821644512545abbd6e415e831d27dccaedd991d9c487aa18fa9
```

This isn't the prettiest, but I hope it demonstrates what I'm trying:

```rust
#[derive(Clone, Debug)]
struct MyValue(Value);

impl Source for MyValue {
    fn clone_into_box(&self) -> Box<dyn Source + Send + Sync> {
        Box::new((*self).clone())
    }

    fn collect(&self) -> std::result::Result<HashMap<String, Value>, ConfigError> {
        match &self.0.kind {
            ValueKind::Table(t) => Ok(t.clone()),
            _ => unimplemented!(),
        }
    }
}

pub fn load_config(profile: Option<&str>, api_key: Option<&str>) -> Result<Self, ConfigError> {
  let mut settings = config::Config::default();

  // Add file sources in here...

  // File sources all set up.
  let profiles = settings.get_table("profiles")?; 

  for (profile_name, profile_settings) in profiles {
      if should_load(profile_name) {
        let profile = MyValue(v);

        settings.merge(profile);
    }
  }

  Ok(settings.try_into()?)
}
```

Unfortunately, the `ValueKind` enum isn't actually exposed, so without modification I can't pattern match on it to implement `Source`. Naturally the above code will fail if the config structure doesn't exactly match, since the `Source` implementation is very narrowly implemented. But, hopefully it illustrates what I'm looking to achieve.
