### ISSUE TITLE
Support default config file convention

### ISSUE THREAD

**Issue by yonipeleg33** [mehcode/config-rs#220]
#### Suggestion
Supporting some default file that the `Config` struct will try to load by default, for example `application.toml`.
The `Config` struct will look for this file anywhere in the project and load it into the desired struct (i.e `Settings` in this example).
A nice feature is to have `application-<env>.toml` that will load the correct file automatically according to an env variable / run argument - For example, `application-dev.toml` will be loaded when `APP_ENVIRONMENT=dev` is set.
The code I imagine looks like so (inspired by [this example](https://github.com/mehcode/config-rs/blob/master/examples/hierarchical-env/src/settings.rs))
```rust
// src/settings.rs
use std::env;
use config::{ConfigError, Config, File, Environment};

#[derive(Debug, Deserialize)]
struct Database {
    url: String,
}

#[derive(Debug, Deserialize)]
struct Sparkpost {
    key: String,
    token: String,
    url: String,
    version: u8,
}

#[derive(Debug, Deserialize)]
struct Twitter {
    consumer_token: String,
    consumer_secret: String,
}

#[derive(Debug, Deserialize)]
struct Braintree {
    merchant_id: String,
    public_key: String,
    private_key: String,
}

#[derive(Debug, Deserialize)]
pub struct Settings {
    debug: bool,
    database: Database,
    sparkpost: Sparkpost,
    twitter: Twitter,
    braintree: Braintree,
}
```
```rust
// src/main.rs
use settings::Settings;
use config::{Config,ConfigError};

fn main() -> Result<(), ConfigError> {
    // Searching for `application.toml` somewhere in the project
    let settings = Config::new::<Settings>()?;

    // Print out our settings
    println!("{:?}", settings);
}
```
```toml
# <somewhere in this project>/application.toml
[database]
url = "postgres://postgres@localhost"

[sparkpost]
key = "sparkpost-dev-key"
token = "sparkpost-dev-token"
url = "https://api.sparkpost.com"
version = 1

[twitter]
consumer_token = "twitter-dev-consumer-key"
consumer_secret = "twitter-dev-consumer-secret"

[braintree]
merchant_id = "braintree-merchant-id"
public_key = "braintree-dev-public-key"
private_key = "braintree-dev-private-key"
```
---

#### Motivation
I cannot help but notice the resemblance of this crate to Spring Boot's `Configuration` mechanism - From which my suggestion is influenced directly. If you're familiar with Spring Boot, it provides the exact same mechanism that I described.
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
