### ISSUE TITLE
Enable placeholders on configuration files

### ISSUE THREAD

**Issue by FaveroFerreira** [mehcode/config-rs#345]
### Feature description
Ability to declare placeholder values in our configuration files that will be taken from the environment variables.

### Use Case
Sometimes we do not decide how our environment variables will be named, so we don't get to define them with prefixes like `APP__`

It would be nice if we could declare placeholders in our configuration files where the values should be taken from our environment variables.

Example:
```yaml
application_port: ${PORT} #value taken from PORT environment variable
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "${DB_PASS}" #value taken from DB_PASS environment variable
  database_name: "${DB_HOST}" #value taken from DB_HOST environment variable
  require_ssl: false
```

**Comment by matthiasbeyer** [comment]
Sounds like something for the "re-thinking" ideas list, thus I added it to the project. I guess we could add (optional) support for templating engines, which would easily resolve this feature request. Adding own logic that does such replacements would be overkill and out of scope for this crate, IMO, but I like the idea of exposing enough interfaces so that a user can easily add templating to the loading/parsing logic of config-rs!

**Comment by FaveroFerreira** [comment]
Nice to hear that!

Comming from an Java + Spring background, maybe I am kinda biased towards using placeholders the way I pointed out on the issue description.

Just out of curiosity, do you have a different approach in mind? Maybe I can try and implement it.

**Comment by matthiasbeyer** [comment]
I do not yet have anything specific in mind, no. If you like to experiment (emphasis on "experiment"), have a look at the rethinking issues. There's a branch linked somewhere where I am exploring my ideas.

**Comment by holmofy** [comment]
I also have a background in Java+Spring. Spring has a very good configuration mechanism. 

https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html

Recently, I saw that the Rust ecosystem has a loco.rs project, which also supports placeholder configuration.

The implementation of [loco.rs](https://github.com/loco-rs/loco) is a good reference. 

https://loco.rs/docs/getting-started/config/

**Comment by epage** [comment]
@awgroeneveld made a draft of this in #706

**Comment by wexder** [comment]
This would be great to allow users of services to template configuration files and allow loading of arbitrary variables defined by user.
For example:
```yaml
sources:
  - type: type1
    url: http://example.com
    headers:
      authoriztion: ${EXAMPLE_PASSWORD}
  - type: type2
    url: http://example2.com
    headers:
      authoriztion: ${EXAMPLE2_PASSWORD}
```

Currently this can be handled by loading the file manually, templating env vars and passing it to  `config::File::from_str`. But this also requires manual resolving of file format.

One might be able to to use `config::FileSourceString` but I couldn't figure out how.


> [@awgroeneveld](https://github.com/awgroeneveld) made a draft of this in [#706](https://github.com/rust-cli/config-rs/pull/706)

I've also look at the proposed solution and I think it should also allow for escaping of the templates, so that it can be passed down to the application.

Edit: wording
