### ISSUE TITLE
Parse encrypted fields / custom transformers

### ISSUE THREAD

**Issue by gitmalong** [mehcode/config-rs#576]
I would like to transform field values that start with a certain prefix during deserialization. 

```yaml
fields:
   some: thing
   some_secret: ENC(<encrypted value>)
```

Is this already possible?
